spring.application.name=careerconnect-backend
spring.datasource.url=jdbc:mysql://localhost:3306/careerconnect
spring.datasource.username=root
spring.datasource.password=ani@_1430

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
